### ISSUE TITLE
Oracle 时间查询路由

### ISSUE THREAD

**Issue by edenpan** [ly164608001/shardingsphere-integrate#1]
你好，我想要用时间字段作为shardingkey来进行路由，但是我用以下的sql的时候，似乎被解析成为了Function segment，然后就不会作为shardingcondition进行查询路由，最后还是全路由查询了。
sql很简单：
`SELECT
            *
        FROM TRADE_LIST
        WHERE 1 = 1
          AND TRADE_DATE = to_date('2021-12-01','yyyy-MM-dd')`

想请教下，你在使用oracle的时候是否有用date字段进行路由的方式，是不是我使用的方式不太对？ 
感谢。

**Comment by ly164608001** [comment]
有的，我们业务场景就是以日期作为分片键，实现上可以参考DateShardingAlgorithm类。

**Comment by edenpan** [comment]
我目前是使用的shardingsphere内置的interval 算法分片。分表是可以解析出来的。
但是查询的时候，由于时间查询需要用  to_date() 函数，感觉是没有办法获取到对应的sharding value，然后就没有进入到算法的sharding函数里面。
比如，如果我使用： 
`SELECT
            *
        FROM TRADE_LIST 
        WHERE 1 = 1
          AND TRADE_DATE = '2021-12-01 00:00:00.000'`
这个查询sql，是可以产生 一个sql  来查询的：
`SELECT
            *
        FROM TRADE_LIST_202112
        WHERE 1 = 1
          AND TRADE_DATE = '2021-12-01 00:00:00.000'`
但是这个sql 在oracle其实并不对，会报错。
不知道是否可以再给点建议？ 谢谢

**Comment by ly164608001** [comment]
查询时添加to_date()函数确实是无法获取到对应的分片值，建议可以把查询字段设置成LocalDateTime类型，就无需添加日期转换函数，就可以解决问题

**Comment by edenpan** [comment]
好的 感谢，我试试。
